package com.jellybrains.quietspace.common_service.enums;

public enum EventType {
    CONNECT,
    DISCONNECT,
    DELETE_MESSAGE,
    SEEN_MESSAGE,
    SEEN_NOTIFICATION,
    JOINED_CHAT,
    LEFT_CHAT,
    EXCEPTION,
    PROFILE_DELETION_REQUEST,
    PROFILE_CREATION_REQUEST,
    PROFILE_DELETION_FAILED,
    PROFILE_CREATION_FAILED,
    PROFILE_DELETED,
    PROFILE_CREATED,
    USER_CREATED, USER_CREATION_FAILED
}